server:
    port: 8084
    contextPath: /utilsweb
security:
    basic:
        enabled: false
#    oauth2:
#           resource:
#               jwt:
#                   key-uri: "http://localhost:9091/user/oauth/token_key"